---
- name: build server
  hosts: webservers
  gather_facts: no
  sudo: yes
  tasks:
    - name: update apt
      apt: update_cache=yes



- name: install apps
  hosts: webservers
  sudo: yes
  roles:
     - ansible-scala
     - ansible-activator

